[package]
name = "file_time_update"
version = "0.1.0"
edition = "2021"

[dependencies]
gpui = "0.2.2"
anyhow = "1.0.75"
chrono = { version = "0.4", features = ["serde"] }
filetime = "0.2"
rfd = "0.14"
walkdir = "2.5.0"
thiserror = "1.0.61"
log = "0.4.0"
pretty_env_logger = "0.5.0"
